services:
  traefik:
    restart: always
    image: traefik:3.6
    ports:
      - 80:80
      - 443:443
      - 8000:8000
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesResolvers.letsencrypt.acme.email=ssl@kontextwork.de"
      - "--certificatesResolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesResolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
    environment:
      CF_DNS_API_TOKEN: ${CF_API_TOKEN}
    volumes:
      - certs:/mnt/certs
      - filestorage:/mnt/filestorage
      - acme:/mnt/acme
      # mount our docker socket so our docker container can be discovered
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  certs:
  filestorage:
  acme:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU:-1500}
