version: '3'

services:
  traefik:
    restart: always
    image: eugenmayer/traefik:2.x
    ports:
      - 80:8080
      - 443:8443
      - 8000:8000
    environment:
      TRAEFIK_ACME_ENABLE: 'true'
      TRAEFIK_ACME_CHALLENGE: 'dns'
      TRAEFIK_ADMIN_SSL: 'false'
      TRAEFIK_ADMIN_ENABLE: 'false'

      TRAEFIK_ACME_CHALLENGE_DNS_PROVIDER: '${TRAEFIK_ACME_CHALLENGE_DNS_PROVIDER}'
      TRAEFIK_ACME_CHALLENGE_DNS_CREDENTIALS: '${TRAEFIK_ACME_CHALLENGE_DNS_CREDENTIALS}'

      ### basic provider setup
      TRAEFIK_HTTPS_ENABLE: 'only'
      TRAEFIK_DOCKER_ENABLE: 'true'
      TRAEFIK_DOCKER_EXPOSEDBYDEFAULT: 'false'
    volumes:
      - certs:/mnt/certs
      - filestorage:/mnt/filestorage
      - acme:/mnt/acme
      # mount our docker socket so our docker container can be discovered
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  certs:
  filestorage:
  acme:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU:-1500}
