services:
  chartmuseum:
    restart: always
    image: ghcr.io/helm/chartmuseum:v0.16.3
    environment:
      STORAGE: local
      STORAGE_LOCAL_ROOTDIR: /charts
      BASIC_AUTH_USER:
      BASIC_AUTH_PASS:
      AUTH_ANONYMOUS_GET:
    volumes:
      - charts:/charts
    labels:
      - "traefik.http.routers.chart.rule=Host(`${CHART_DOMAIN}`)"
      - "traefik.http.routers.chart.service=chart"
      - "traefik.http.routers.chart.tls=true"
      - "traefik.http.routers.chart.tls.certresolver=letsencrypt"
      - "traefik.http.services.chart.loadbalancer.server.scheme=http"
      - "traefik.http.services.chart.loadbalancer.server.port=8080"
      - "traefik.enable=true"
volumes:
  charts:
