version: '3'

services:
  chartmuseum:
    restart: always
    image: ghcr.io/helm/chartmuseum:v0.13.1
    environment:
      STORAGE: local
      STORAGE_LOCAL_ROOTDIR: /charts
      BASIC_AUTH_USER:
      BASIC_AUTH_PASS:
      AUTH_ANONYMOUS_GET:
    volumes:
      - charts:/charts
    labels:
      traefik.http.services.chartmuseum.loadbalancer.server.port: 8080
      traefik.http.routers.chartmuseum.rule: 'Host(`${CHART_DOMAIN}`)'
      traefik.http.routers.chartmuseum.tls: 'true'
      traefik.http.routers.chartmuseum.tls.certresolver: 'default'
      traefik.enable: 'true'
volumes:
  charts:
